# Generated by Django 4.2 on 2023-05-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='username',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('client', 'Client')], default='client', max_length=255, unique=True),
        ),
    ]
