# Generated by Django 4.2 on 2023-05-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_usermodel_email_alter_usermodel_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='user_role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('client', 'Client')], default='client', max_length=10),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
