# Generated by Django 4.2 on 2023-05-03 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveSubstances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Manufactures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.categories', verbose_name='категория')),
            ],
        ),
        migrations.CreateModel(
            name='Medicines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('country', models.CharField(max_length=255, verbose_name='Страна производителя')),
                ('representative', models.CharField(max_length=255, verbose_name='Представитель')),
                ('image', models.ImageField(upload_to='medicine', verbose_name='Изображение')),
                ('code_atx', models.CharField(max_length=255, verbose_name='Штрих-код')),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('active_substances', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.activesubstances', verbose_name='активные вещества')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.categories', verbose_name='категория')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.manufactures', verbose_name='Производитель')),
            ],
        ),
    ]
