# Generated by Django 4.2 on 2023-05-04 11:15

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_order_orderitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activesubstances',
            options={'verbose_name': 'Активные вещества', 'verbose_name_plural': 'Активные вещества'},
        ),
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='manufactures',
            options={'verbose_name': 'Производитель', 'verbose_name_plural': 'Производители'},
        ),
        migrations.AlterModelOptions(
            name='medicines',
            options={'verbose_name': 'Добавление', 'verbose_name_plural': 'Добавление'},
        ),
        migrations.AddField(
            model_name='medicines',
            name='available',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicines',
            name='stock',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='medicines',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='medicines',
            name='image',
            field=models.ImageField(upload_to='medicine/%Y/%m/%d', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='medicines',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
