# Generated by Django 4.2 on 2023-05-04 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_alter_activesubstances_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicines',
            name='available',
        ),
    ]
